Algoritmo "Divisao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Santos
// Descrição   : Pega dois numeros, divide e traz o resultado
// Autor(a)    : Giovanna Savoretti
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
 numero1: real
 numero2: real
 divisao:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Programa de Divisão")
 Escreva ("Escreva o primeiro número: ")
 Leia(numero1)
 Escreva ("Escreva o segundo número: ")
 Leia (numero2)
 divisao<-numero1/numero2
 Escreva("O resultado da divisão é: ", divisao)

Fimalgoritmo