Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Calcula o antecessor de um número
// Autor(a)    : Giovanna Savoretti
// Data atual  : 31/08/2026
Var
// Seção de Declarações das variáveis 
   numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Antecessor do 5")
Escreva ("Digite o primeiro número: ")
Leia (numero)
numero<- numero-1
Escreva ("O valor é: ", numero)


Fimalgoritmo