Algoritmo "Exercicio27"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos
// Descrição   : Ler um valor e escrever se é positivo, negativo ou zero
// Autor(a)    : Giovanna Savoretti
// Data atual  : 12/09/2026
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval ("Digite um número:" )
   Leia (numero)
   Se numero > 1 entao
      Escreval ("É um número positivo")
   Senao
      Se numero < 0 entao
         Escreval ("É um número negativo")
      Senao
         Escreval ("Número 0")
      Fimse
   Fimse

Fimalgoritmo
