Algoritmo "Exercício14"
// Disciplina   :  Lógica de programação com JavaScript
// Professor   : Jailson Costa
// Descrição   :  Ler um valor e escrever a mensagem É MAIOR QUE 10! se o
// valor lido for maior que 10, caso contrário escrever NÃO É MAIOR QUE 10!
// Autor(a)    : Giovanna Savoretti
// Data atual  : 31/08/2026
// Seção de Declarações das variáveis

Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval ("Digite um número: ")
   Leia (numero)
   se numero> 10 entao
      Escreval ("É maior que 10!")
   senao
      Escreval("É menor que 10!")
   fimse

Fimalgoritmo