Algoritmo "AreaRetangular"
// Disciplina   : Lógica de Programação de JavaScript
// Professor   : Jailson Costa
// Descrição   : Calcula o numero do sucessor
// Autor(a)    : Giovanna Savoretti
// Data atual  : 31/08/2026
Var
// Seção de Declarações das variáveis 
  altura, base, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval ("Digite a altura: ")
  Leia (altura)
  Escreva ("Digite a base: ")
  Leia (base)
  area<- base*altura
  Escreva ("A área do retangulo é: ", area, " metros")

Fimalgoritmo