Algoritmo "Exercício12"
// Disciplina   : [Lógica de Programação em JavaScript]
// Professor   : Jailsom Costa
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    :Giovanna Savoretti
// Data atual  : 04/09/2026
Var
   // Seção de Declarações das variáveis
   fahrenheit: real
   celsius: real
   c: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval ("Digite a temperatura em Fahrenheit: ")
   leia (fahrenheit)
   celsius <- (fahrenheit - 32) * 5 / 9
   Escreval ("O valor em Celsius é: ", celsius, "ºC")

Fimalgoritmo