Algoritmo "Exercicio1"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos
// Descrição   : a) Ler uma temperatura em graus Celsius e apresentá-la
// convertida em graus Fahrenheit. A fórmula de conversão é F 
//(9 * C + 160) / 5, sendo F a temperatura em Fahrenheit e C a
//temperatura em Celsius
// Autor(a)    : Giovanna Savoretti
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
   celsius, fahrenheit: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval ("Programa Celsius em Fahrenheit")
  Escreval ("")
  Escreval ("Digite a temperatura em graus Celsius: ")
  Leia (celsius)
  fahrenheit <- (9 * celsius + 160) / 5
  Escreval ("O grau Celsius", celsius, "° em Fahrenheit é: ", fahrenheit, "°")



Fimalgoritmo