Algoritmo "Exercício3"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos
// Descrição   : c) Calcular e apresentar o valor do volume de uma lata de
// óleo, utilizando a fórmula:

// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2026
Var
// Seção de Declarações das variáveis 
    altura, largura, raio, volume: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval ("Digite a altura da lata de óleo: ")
   Leia (altura)
   Escreval ("Digite a largura da lata de óleo: ")
   Leia(largura)
   raio <- largura / 2
   volume <- 3.14 * raio ^ 2 * altura
   Escreval ("O volume da lata de óleo é: ", volume)



Fimalgoritmo