Algoritmo "Exercicio8"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jaison Santos
// Descrição   : Elaborar um programa que calcule e apresente
// o volume de uma caixa retangular, por meio da fórmula
// VOLUME <- COMPRIMENTO * LARGURA * ALTURA.
// Autor(a)    : Giovanna Savoretti
// Data atual  : 23/09/2026
Var
// Seção de Declarações das variáveis 
    comprimento, largura, altura, volume: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Escreval ("----Calcule o volume de um Retângulo----")
     Escreval ("Digite o comprimento da caixa retangular: ")
     Leia (comprimento)
     Escreval ("Digite a largura da caixa retangular: ")
     Leia (largura)
     Escreval ("Digite a altura da caixa retangular: ")
     Leia (altura)
     volume <- comprimento * largura * altura

     Escreval ("O volume da caixa retangular é: ", volume)

Fimalgoritmo