Algoritmo "Exercicio9"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos
// Descrição   : Ler dois inteiros (variáveis A e B) e imprimir o resultado
// do quadrado da diferença do primeiro valor pelo segundo.
// Autor(a)    : Giovanna Savoretti
// Data atual  : 23/09/2026
Var
   // Seção de Declarações das variáveis
   A, B: inteiro
   quadradoDaDiferenca: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval ("Digite o primeiro número inteiro: ")
   Leia (A)
   Escreval ("Digite o segundo ´numero inteiro: ")
   Leia (B)
   quadradoDaDiferenca <- (A - B) ^ 2

   Escreval ("O quadrado da diferença desses números é: ", quadradoDaDiferenca)

Fimalgoritmo