Algoritmo "Exercicio12"
// Disciplina   : [Lógica de Programação em JavaScript]
// Professor   : Jailson Santos
// Descrição   : Elaborar um programa que efetue a leitura de três valores
//(A, B e C) e apresente como resultado final à soma dos quadrados dos
// três valores lidos.
// Autor(a)    : Giovanna Savoretti
// Data atual  : 23/09/2026
Var
// Seção de Declarações das variáveis
   A, B, C: inteiro
   somaDosQuadrados: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
  Escreval ("Digite o primeiro número: ")
  Leia (A)
  Escreval ("Digite o segundo número: ")
  Leia (B)
  EScreval ("Digite o terceiro número: ")
  Leia (C)

  somaDosQuadrados <- A^2 + B^2 + C^2

  Escreval ("Soma dos quadrados dos três termos: ", somaDosQuadrados)


Fimalgoritmo