Algoritmo "L03B"
// Disciplina   : [Lógica de Programação em JavaScript]
// Professor   : Jailson Santos
// Descrição   : b) Apresentar o total da soma obtida dos cem primeiros
// números inteiros (1+2+3+4+...+98+99+100).
// Autor(a)    : Giovanna Savoretti
// Data atual  : 23/09/2026
Var
   // Seção de Declarações das variáveis
   soma, resultado: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   
   soma <- 1
   enquanto (soma <=100) faca
      resultado <- resultado + soma
      soma <- soma + 1
   fimenquanto
      Escreval ("O total da soma dos cem primeiros números é: ", resultado)


Fimalgoritmo