Algoritmo "L03H"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos

// Descrição   : Elaborar um programa que apresente os valores de conversão
// de graus Celsius em Fahrenheit, de 10 em 10 graus, iniciando a contagem
// em 10 graus Celsius e finalizando em 100 graus Celsius. O
// programa deve apresentar os valores das duas temperaturas. A fórmula de
//conversão é.. sendo F a temperatura em Fahrenheit e C a temperatura em
//Celsius.

// Autor(a)    : Giovanna Savoretti
// Data atual  : 25/09/2026
Var
// Seção de Declarações das variáveis 
     celsius: inteiro
     fahrenheit: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       celsius <- 10

       
       enquanto celsius <= 100 faca
       fahrenheit <- (9 * celsius + 160)/5
       Escreval ("Celsius ", celsius, "ºC e Fahrenheit: ", fahrenheit, "ºF")
       celsius <- celsius + 10
       fimenquanto
       


Fimalgoritmo