Algoritmo "L05A"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos

// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.

// Autor(a)    : Giovanna Savoretti
// Data atual  : 27/09/2026
Var
   // Seção de Declarações das variáveis
   contadora, quadrado: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para contadora de 15 ate 200 faca
      quadrado <- contadora * contadora
      Escreval ("O quadro de", contadora, " é: ", quadrado)
   fimpara

Fimalgoritmo