Algoritmo "L05B"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos

// Descrição   : Apresentar os resultados de uma tabuada de multiplicar
// (de 1 até 10) de um número qualquer.

// Autor(a)    : Giovanna Savoretti
// Data atual  : 27/09/2026
Var
   // Seção de Declarações das variáveis
    contadora, numero, multiplicador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   Escreval ("Digite um número para calcular a tabuada de 1 até 10: ")
   Leia (numero)
   Escreval ("")

   para contadora de 1 ate 10 faca
      multiplicador <- numero * contadora
      Escreval (numero, " x", contadora, " =", multiplicador)
   fimpara


Fimalgoritmo