Algoritmo "L05C"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos

// Descrição   : Apresentar o total da soma obtida dos cem primeiros
// números inteiros (1+2+3+4+...+98+99+100).

// Autor(a)    : Giovanna Savoretti
// Data atual  : 27/09/2026
Var
   // Seção de Declarações das variáveis
   contadora, somatorio: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   Para contadora de 1 ate 100 faca
      somatorio <- somatorio + contadora
   Fimpara

   Escreval ("Total da soma obtida dos cem primeiros números inteiros: ", somatorio)

Fimalgoritmo