Algoritmo "L05D"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos

// Descrição   : Elaborar um programa que apresente no final o somatório
// dos valores pares existentes na faixa de 1 até 500

// Autor(a)    : Giovanna Savoretti
// Data atual  : 27/09/2026
Var
   // Seção de Declarações das variáveis
      contadora, somatorio: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   Para contadora de 2 ate 500 passo 2 faca
         somatorio <- somatorio + contadora
   Fimpara
   
   Escreval ("Somatório dos números pares de 1 até 500: ", somatorio)

Fimalgoritmo