Algoritmo "L05E"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos

// Descrição   : Apresentar todos os valores numéricos inteiros ímpares
// situados na faixa de 0 a 20. Para verificar se o número é ímpar, efetuar
// dentro da malha a verificação lógica desta condição com a instrução
// se, perguntando se o número é ímpar; sendo, mostre-o; não sendo, passe
// para o próximo passo.

// Autor(a)    : Giovanna Savoretti
// Data atual  : 27/09/2026
Var
   // Seção de Declarações das variáveis
        contadora: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   Para contadora de 0 ate 20 faca
      Se (contadora %2 <> 0) entao
         Escreval (contadora)
      Fimse
   Fimpara

Fimalgoritmo