Algoritmo "L05G"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Santos

// Descrição   : Apresentar os resultados das potências de 3, variando do
//expoente 0 até o expoente 15. Deve ser considerado que qualquer número
// elevado a zero é 1, e elevado a 1 é ele próprio. Observe que neste
//exercício não pode ser utilizado o operador de exponenciação do portuguol (^)

// Autor(a)    : Giovanna Savoretti
// Data atual  : 27/09/2026
Var
   // Seção de Declarações das variáveis
   contadora, potencia: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   potencia <- 1

   Para contadora de 0 ate 15 faca
      Escreval ("3 elevado a ", contadora, " = ", potencia)
      potencia <- potencia * 3
   Fimpara

Fimalgoritmo