Algoritmo "Mensagem"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Santos
// Descrição   : Exibe uma mensagem na tela
// Autor(a)    : Giovanna Savoretti
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      Escreva("Digite o seu nome:")
      Leia (nome)
      Escreva("Seja bem vindo (a) ", nome)

Fimalgoritmo