Algoritmo "Multiplicacao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Santos
// Descrição   : Calculo de produtos.
// Autor(a)    : Giovanna Savoretti
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
  numero1: inteiro
  numero2: inteiro
  multiplicacao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval("Programa de Multiplicação")
  Escreva ("Escreva o primeiro número: ")
  Leia (numero1)
  Escreva ("EScreva o segundo número: ")
  Leia (numero2)
  multiplicacao<-numero1*numero2
  Escreva("O resultado do produto é: ", multiplicacao)

Fimalgoritmo