Algoritmo "Soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Faz calculos de soma
// Autor(a)    : Giovanna Savoretti
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
 numero1:inteiro
 numero2:inteiro
 soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval("Programa Soma")
  Escreva("Escreva o primeiro numero: ")
  Leia (numero1)
  Escreva("Escreva o segundo numero: ")
  Leia (numero2)
  soma<-numero1+numero2
  Escreva("A soma dos numeros digitados é: ", soma)

Fimalgoritmo