Algoritmo "Subtração"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Santos
// Descrição   : Faz calculo de subtração
// Autor(a)    : Giovanna Savoretti
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
  numero1: inteiro
  numero2: inteiro
  subtracao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Conta de subtração")
Escreva("Escreva o primeiro número: ")
Leia (numero1)
Escreva ("Escreva o segundo número: ")
Leia (numero2)
subtracao<-numero1-numero2
Escreva ("O resultado é: ", subtracao)

Fimalgoritmo